### ISSUE TITLE
OOS concerns

### ISSUE THREAD

**Issue by ProditorMagnus** [fluffbeast/Recall_Cost#1]
- [x] needs to be require_modification=yes since there are custom unit types
- [x] I believe this will cause OOS if some players have campaigns while others do not - if wesnoth.unit_types[unit_name] ~= nil - might need to use wesnoth.synchronize_choice to make sure all current players have that unit, but even then players might change during game

**Comment by fluffbeast** [comment]
The list of level zero units and magelike advances now includes only core units. Wose Sapling is included only when the wesnoth version >= 1.15.1, since that's when it was added to core.

The code to check if units are present has been removed.
